// Layer 1: the deterministic scaffold.
//
// The plan's rule, verbatim: "Layer 1 deterministic, no key, no spend: architecture cards
// from the import graph and directory tree, dependency census, gate discovery,
// conventions measured statistically, history and ownership stats. Every unit cites the
// repo, reproducible, marked generated. Layer 1 alone enables retrieval and MCP."
//
// Four properties are enforced by construction rather than by review:
//
//   Cited. Every unit names the files or commits it was computed from, and the citations
//   are checked against the real tree by validateCitations() before the unit can be
//   ingested. A generated unit that cites a file which does not exist is worse than no
//   unit: it is a confident wrong answer with the repo's own authority behind it.
//   Reproducible. No clock, no random, no directory-order dependence. Two runs over the
//   same tree produce identical bytes, which is what makes `evidenceDigest` a real
//   check rather than decoration.
//   Marked generated. meta.generated is true on every unit and the provenance section is
//   part of the CONTENT, so a reader who sees only the retrieved text still knows a
//   machine wrote it and how to re-derive it.
//   Silent about what it cannot know. errors.md STARTS EMPTY. Layer 1 mines no lessons,
//   not even from a history full of fix commits: mining those into prose is Layer 2's
//   job, behind the spend boundary, and inventing an error record is the one thing the
//   plan forbids outright.
import { createHash } from 'node:crypto';

import { compareStrings } from './walk.js';

/** Namespace for generated units. Deliberately not `global.`, which is the standing pin
 *  prefix: a generated card that accidentally became a standing unit would ride outside
 *  the token budget on every query forever. */
export const UNIT_NAMESPACE = 'daijin';

/** Where generated units claim to live. A virtual path: nothing is written to the repo. */
export const UNIT_PATH_ROOT = '.daijin/brain';

export const GENERATOR = 'daijin-layer1';

/** Cap on architecture cards, reported when it bites. */
export const DEFAULT_AREA_CARD_LIMIT = 60;

export function slug(value) {
  return String(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80) || 'unnamed';
}

function sha256(text) {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

/**
 * Assemble one unit from its parts.
 *
 * `core` is the span the content-survival gate checks for verbatim presence after the
 * retrieval budget trim. It is the claim plus its citations, not just the headline: a
 * card whose claim survives while its cited paths are truncated away has lost the only
 * thing that made it checkable, and reporting that as survival is exactly the kind of
 * gate that cannot fail.
 */
function unit({ id, type, title, area, tags, sections, core, citations, evidence }) {
  const body = sections.filter(Boolean).join('\n\n');
  const content = `# ${title}\n\n${body}`;
  return {
    id,
    type,
    path: `${UNIT_PATH_ROOT}/${type}/${id.split('.').slice(2).join('.') || slug(title)}.md`,
    title,
    tags,
    body,
    content,
    contentHash: sha256(content),
    core,
    citations,
    meta: {
      area,
      generated: true,
      generator: GENERATOR,
      layer: 1,
      citations,
      evidenceDigest: sha256(JSON.stringify(evidence)),
    },
  };
}

function provenanceSection(method, digest) {
  return [
    '## Provenance',
    '',
    `Generated by Daijin Layer 1. Deterministic, no model, no network.`,
    `Method: ${method}`,
    `Reproduce: re-run daijin init on this repo at the same commit; identical input produces identical bytes.`,
    `Evidence digest: ${digest}`,
  ].join('\n');
}

function bullet(lines, empty) {
  return lines.length ? lines.map((line) => `- ${line}`).join('\n') : `- ${empty}`;
}

// ---------------------------------------------------------------------------------
// Architecture cards, one per area
// ---------------------------------------------------------------------------------

function architectureCard(areaEntry, evidence, limits) {
  const { area, files, fileCount, importsOut, importedBy, external, builtins = [], inDegree, outDegree } = areaEntry;
  const totalSource = evidence.graph.edges.length >= 0 ? evidence.symbols.byFile.size : 0;
  const symbolLines = files
    .flatMap((file) => (evidence.symbols.byFile.get(file) || []).map((name) => `${name} (${file})`))
    .slice(0, limits.symbols);
  const fileLines = files.slice(0, limits.filesPerCard).map((file) => {
    const inbound = evidence.graph.inDegree.get(file) || 0;
    const outbound = evidence.graph.outDegree.get(file) || 0;
    return `${file} (imported by ${inbound}, imports ${outbound})`;
  });
  const truncatedFiles = files.length - fileLines.length;

  const claim = `Claim: ${area} holds ${fileCount} source ${fileCount === 1 ? 'file' : 'files'}, `
    + `imports ${importsOut.length} other ${importsOut.length === 1 ? 'area' : 'areas'} `
    + `(${outDegree} file-level references out), and is imported by ${importedBy.length} `
    + `(${inDegree} references in).`;
  const evidenceLine = `Evidence: import graph over ${totalSource} parsed source files, directory tree, `
    + `and the tracked file list (${evidence.files.source}).`;
  // The file list is a plain block INSIDE the claim section rather than its own `##`
  // heading, and that is a chunking decision, not a formatting one: chunkDocument splits a
  // windowed unit at every heading, so a `## Files` heading would put the claim in one
  // chunk and its citations in another. The retrieval path substitutes the winning CHUNK
  // for an architecture document (rank.js:126), so an engineer would then receive a claim
  // with no evidence, or evidence with no claim, depending on which window won.
  const filesBlock = ['Files in this module:', '', bullet(fileLines, 'none'),
    truncatedFiles > 0 ? `\n(${truncatedFiles} further ${truncatedFiles === 1 ? 'file' : 'files'} in this area, omitted from this card)` : '']
    .filter(Boolean).join('\n');

  // The core is the claim, its evidence line, and the cited files: one contiguous span in
  // one chunk. This is what the survival gate demands back verbatim.
  const core = `${claim}\n${evidenceLine}\n\n${filesBlock}`;
  const digestInput = { area, files, importsOut, importedBy, external, builtins, inDegree, outDegree };

  return unit({
    id: `${UNIT_NAMESPACE}.architecture.${slug(area)}`,
    type: 'architecture',
    title: `Module: ${area}`,
    area,
    tags: ['architecture', 'generated', slug(area)],
    sections: [
      core,
      `## Imports from\n\n${bullet(importsOut.map((entry) => `${entry.name} (${entry.count} references)`), 'nothing in this repo')}`,
      `## Imported by\n\n${bullet(importedBy.map((entry) => `${entry.name} (${entry.count} references)`), 'nothing in this repo')}`,
      `## External packages used here\n\n${bullet(external.slice(0, limits.externals).map((entry) => `${entry.name} (${entry.count} files)`), 'none')}`,
      `## Node built-ins used here\n\n${bullet(builtins.slice(0, limits.externals).map((entry) => `${entry.name} (${entry.count} files)`), 'none')}`,
      `## Exported symbols\n\n${bullet(symbolLines, 'none found by the deterministic scan')}`,
    ],
    core,
    citations: files.slice(0, limits.filesPerCard),
    evidence: digestInput,
  });
}

// ---------------------------------------------------------------------------------
// Dependency census card
// ---------------------------------------------------------------------------------

function dependencyCard(evidence) {
  const census = evidence.dependencies;
  const manifests = [...new Set(census.declared.flatMap((row) => row.manifests))].sort();
  const claim = `Claim: ${census.declaredCount} declared ${census.declaredCount === 1 ? 'dependency' : 'dependencies'}, `
    + `${census.usedRatio.display} imported by at least one source file, `
    + `${census.unusedDeclared.length} declared and never imported, `
    + `${census.undeclaredImports.length} imported and never declared.`;
  const evidenceLine = `Evidence: ${manifests.length ? manifests.join(', ') : 'no manifest found'} `
    + `crossed with the import graph over ${evidence.symbols.byFile.size} parsed source files.`;
  // Same chunking rule as the area cards: the cited manifest entries stay in the claim's
  // own section so the claim and its evidence cannot be split across two windows.
  const usedBlock = ['Declared and used:', '', bullet(
    census.declared.filter((row) => row.importedByFiles > 0).slice(0, 60)
      .map((row) => `${row.name} ${row.versions.join(' ')} (${row.importedByFiles} files)`),
    'none',
  )].join('\n');
  const core = `${claim}\n${evidenceLine}\n\n${usedBlock}`;

  return unit({
    id: `${UNIT_NAMESPACE}.architecture.dependencies`,
    type: 'architecture',
    title: 'Dependencies',
    area: 'dependencies',
    tags: ['architecture', 'dependencies', 'generated'],
    sections: [
      core,
      `## Declared and never imported\n\n${bullet(census.unusedDeclared.slice(0, 40), 'none')}`,
      `## Imported but not declared\n\n${bullet(
        census.undeclaredImports.slice(0, 40).map((row) => `${row.name} (${row.importedByFiles} files: ${row.files.slice(0, 3).join(', ')})`),
        'none',
      )}`,
    ],
    core,
    citations: manifests,
    evidence: census,
  });
}

// ---------------------------------------------------------------------------------
// Convention cards
// ---------------------------------------------------------------------------------

const CONVENTION_CARDS = [
  {
    key: 'indentation',
    title: 'Indentation',
    rule: (measurement) => `Rule: source files indent with ${measurement.dominant}`
      + `${measurement.width ? `, width ${measurement.width}` : ''}.`,
    method: 'counted per file over indented lines; a file is classified by whichever of tabs or spaces leads it',
  },
  {
    key: 'quotes',
    title: 'String quotes',
    rule: (measurement) => `Rule: JavaScript and TypeScript files prefer ${measurement.dominant} quotes.`,
    method: 'counted per file by comparing single-quoted and double-quoted string literals outside comments',
  },
  {
    key: 'semicolons',
    title: 'Statement terminators',
    rule: (measurement) => `Rule: statements are written ${measurement.dominant === 'with' ? 'with' : 'without'} terminating semicolons.`,
    method: 'counted per file over statement-shaped lines; files with fewer than five such lines are not counted',
  },
  {
    key: 'moduleSystem',
    title: 'Module system',
    rule: (measurement) => `Rule: modules are ${measurement.dominant === 'esm' ? 'ES modules (import and export)' : measurement.dominant === 'cjs' ? 'CommonJS (require and module.exports)' : measurement.dominant}.`,
    method: 'classified per file by which module syntax appears; files using both are counted as mixed',
  },
  {
    key: 'fileNaming',
    title: 'File naming',
    rule: (measurement) => `Rule: source file names are ${measurement.dominant}.`,
    method: 'classified per file name against kebab-case, snake_case, camelCase, PascalCase and lowercase',
  },
];

function conventionCard(card, measurement) {
  const rule = card.rule(measurement);
  const measured = `Measured: ${measurement.measured.display} files, mechanically, over the tracked file list.`;
  const core = `${rule}\n${measured}`;
  const exceptions = measurement.exceptions || [];
  return unit({
    id: `${UNIT_NAMESPACE}.convention.${slug(card.key)}`,
    type: 'convention',
    title: `Convention: ${card.title}`,
    area: 'conventions',
    tags: ['convention', 'generated', slug(card.key)],
    sections: [
      `${rule}\n${measured}`,
      `## Counts\n\n${bullet(
        Object.entries(measurement.counts)
          .sort((left, right) => right[1] - left[1] || compareStrings(left[0], right[0]))
          .map(([name, count]) => `${name}: ${count}`),
        'none',
      )}`,
      `## Exceptions\n\n${bullet(exceptions, 'none found')}`,
      `## How this was measured\n\n${card.method}.`,
    ],
    core,
    // A convention card cites the files that DISAGREE with it, because those are the ones
    // a reader can check the claim against; citing the majority proves nothing.
    citations: exceptions,
    evidence: { key: card.key, counts: measurement.counts, measured: measurement.measured, dominant: measurement.dominant },
  });
}

function testLayoutCard(layout) {
  const rule = `Rule: tests live ${layout.dominant === 'colocated' ? 'beside the code they test' : layout.dominant === '__tests__' ? 'in __tests__ directories' : 'in a top-level test directory'}.`;
  const measured = `Measured: ${layout.measured.display} source files are tests, `
    + `split ${Object.entries(layout.counts).filter(([, count]) => count > 0).map(([name, count]) => `${name} ${count}`).join(', ') || 'no split'}.`;
  return unit({
    id: `${UNIT_NAMESPACE}.convention.test-layout`,
    type: 'convention',
    title: 'Convention: Test layout',
    area: 'conventions',
    tags: ['convention', 'generated', 'tests'],
    sections: [
      `${rule}\n${measured}`,
      `## Example test files\n\n${bullet(layout.sample, 'none')}`,
      '## How this was measured\n\nclassified by path against the three layouts; a file counts as a test when its path or name marks it as one.',
    ],
    core: `${rule}\n${measured}`,
    citations: layout.sample,
    evidence: layout,
  });
}

// ---------------------------------------------------------------------------------
// History and ownership card
// ---------------------------------------------------------------------------------

function historyCard(history) {
  const hottest = history.hotFiles[0];
  const pattern = `Pattern: ${history.commits} commits walked from ${history.authors.length} `
    + `${history.authors.length === 1 ? 'author' : 'authors'}, ${history.firstCommit || 'unknown'} to ${history.lastCommit || 'unknown'}`
    + `${hottest ? `; the most changed file is ${hottest.file} at ${hottest.commits} commits` : ''}.`;
  const measured = `Measured: git log --numstat, ${history.commits} of ${history.total} commits `
    + `(cap ${history.cap}${history.capped ? ', REACHED, so the numbers below cover the most recent window only' : ', not reached'}).`;
  const core = `${pattern}\n${measured}`;
  return unit({
    id: `${UNIT_NAMESPACE}.workflow.history`,
    type: 'workflow',
    title: 'How this repository changes',
    area: 'history',
    tags: ['workflow', 'history', 'generated'],
    sections: [
      `${pattern}\n${measured}`,
      `## Most changed files\n\n${bullet(
        history.hotFiles.slice(0, 20).map((entry) => `${entry.file} (${entry.commits} commits, ${entry.authors} authors, +${entry.added}/-${entry.deleted})`),
        'none',
      )}`,
      `## Files that change together\n\n${bullet(
        history.coChange.slice(0, 20).map((entry) => `${entry.files[0]} with ${entry.files[1]} (${entry.commits} commits)`),
        'no pair changed together often enough to report',
      )}`,
      `## Authors\n\n${bullet(
        history.authors.slice(0, 20).map((entry) => `${entry.name} (${entry.commits} commits, ${entry.files} files)`),
        'none',
      )}`,
      `## Repair activity\n\n${history.fixCommits.length} commits are described as fixes and `
        + `${history.revertCommits.length} as reverts in the window above. They are recorded as evidence and `
        + 'deliberately NOT written up as lessons here: a lesson must be validated against the real commit '
        + 'before it enters the brain, and Layer 1 does no narration.',
    ],
    core,
    citations: history.hotFiles.slice(0, 20).map((entry) => entry.file),
    evidence: {
      commits: history.commits, authors: history.authors, hotFiles: history.hotFiles, coChange: history.coChange,
    },
  });
}

// ---------------------------------------------------------------------------------
// Assembly
// ---------------------------------------------------------------------------------

/**
 * Generate the Layer 1 units.
 *
 * @returns {{ units: object[], errors: object, notes: string[], limits: object }}
 */
export function scaffoldLayer1(evidence, {
  areaCardLimit = DEFAULT_AREA_CARD_LIMIT,
  filesPerCard = 40,
  symbols = 40,
  externals = 20,
} = {}) {
  const limits = { areaCardLimit, filesPerCard, symbols, externals };
  const notes = [];
  const units = [];

  const areas = evidence.areas.filter((area) => area.fileCount > 0);
  if (areas.length > areaCardLimit) {
    notes.push(`${areas.length} areas found, ${areaCardLimit} carded; the cap is displayed rather than applied silently.`);
  }
  for (const area of areas.slice(0, areaCardLimit)) {
    units.push(architectureCard(area, evidence, limits));
  }

  if (evidence.dependencies.declaredCount > 0 || evidence.dependencies.undeclaredImports.length > 0) {
    units.push(dependencyCard(evidence));
  } else {
    notes.push('No dependency card: no manifest declared dependencies and no external imports were found.');
  }

  for (const card of CONVENTION_CARDS) {
    const measurement = evidence.conventions[card.key];
    // A convention with no denominator is not a convention, it is an absence. Emitting a
    // card that says "0 of 0 files" would put a claim in the brain that no measurement
    // supports, which is the failure mode this whole file is arranged against.
    if (!measurement?.dominant || measurement.measured.total === 0) {
      notes.push(`No ${card.key} convention card: nothing measurable (${measurement?.measured.display || '0 of 0'}).`);
      continue;
    }
    units.push(conventionCard(card, measurement));
  }
  if (evidence.testLayout.testFiles > 0) units.push(testLayoutCard(evidence.testLayout));
  else notes.push('No test-layout card: no test files found by path.');

  if (evidence.history.available && evidence.history.commits > 0) {
    units.push(historyCard(evidence.history));
  } else {
    notes.push(`No history card: ${evidence.history.reason || 'no commits walked'}.`);
  }

  // The errors record. EMPTY at Layer 1, always, and the reason is stated rather than
  // implied. The candidate lists ride alongside as evidence for the Layer 2 narration
  // step; nothing here turns one into a unit.
  const errors = {
    units: [],
    reason: evidence.history.available
      ? 'Layer 1 writes no error records. Fix and revert commits are candidate evidence only; a lesson enters the brain after narration validates it against the real commit, or after the gym earns it.'
      : 'errors.md starts empty: this repo has no history to mine, and inventing an error record is forbidden.',
    candidates: {
      fixCommits: evidence.history.fixCommits || [],
      revertCommits: evidence.history.revertCommits || [],
    },
  };

  // The provenance section is appended last so its digest covers the finished card.
  const finished = units.map((entry) => {
    const method = entry.type === 'workflow'
      ? 'git log --numstat walk, capped and reported'
      : entry.type === 'convention'
        ? 'statistical count over the tracked source files'
        : 'import graph and directory tree over the tracked source files';
    const content = `${entry.content}\n\n${provenanceSection(method, entry.meta.evidenceDigest)}`;
    return {
      ...entry,
      content,
      body: `${entry.body}\n\n${provenanceSection(method, entry.meta.evidenceDigest)}`,
      contentHash: sha256(content),
    };
  });

  return { units: finished, errors, notes, limits };
}

/**
 * Reject any unit citing something that is not there.
 *
 * This is the "mechanics accept" half of the plan's rule, and it runs on LAYER 1 output
 * too, not only on narration. A deterministic generator can still cite a stale path when
 * its inputs and the tree disagree (a file read from a cached listing, a path normalised
 * wrongly), and a citation nobody checks is indistinguishable from one nobody can check.
 *
 * @returns {{ accepted: object[], dropped: object[] }}
 */
export function validateCitations(units, { files = [], commits = new Set() } = {}) {
  const fileSet = new Set(files);
  const accepted = [];
  const dropped = [];
  for (const entry of units) {
    const missing = (entry.citations || []).filter((citation) => {
      if (/^[0-9a-f]{7,40}$/i.test(citation)) return !commits.has(citation);
      return !fileSet.has(citation);
    });
    if (missing.length > 0) dropped.push({ id: entry.id, missing });
    else accepted.push(entry);
  }
  return { accepted, dropped };
}
