// Gold-provenance exclusion: the documents the student must not be shown.
//
// Ported from platform/exam/provenance.js. This is the retrieval-side half of "the student
// never sees gold", and until now Daijin had only the output-side half (forbidden strings
// armed at mining validation, which stops the student NAMING the reference and does nothing
// about being handed it).
//
// The hazard is specific and it is not hypothetical. A brain is built from a repository's
// own history and documents. If the gold commit itself wrote a decision record describing
// the change, or edited the section of an architecture document that the change is about,
// then ordinary retrieval hands the student the answer and the exam measures reading
// comprehension. The exclusion is computed per exam and passed into retrieval as
// excludeDocumentIds (Store v3 CandidateFilters, capped at 1000).
//
// THREE RULES, each a different way a document can be downstream of the gold commit:
//
//  1. DIRECT. The document names the gold commit or the exam: front-matter source or commit,
//     an exam reference, or an evaluation document whose content carries the exam id. These
//     are the brain's own records OF the exam, and a gym that writes lessons back creates
//     more of them every cycle.
//  2. SOURCE SECTION CHANGED BY GOLD. The document cites `branch:file#anchor`, the gold
//     commit touched that file, and the section at that anchor DIFFERS between base and
//     gold. Section granularity is deliberate: excluding every document sourced from a
//     touched file would strip legitimate context the student is meant to have, and the
//     platform learned that distinction rather than assuming it.
//  3. INTRODUCED BY GOLD. The document's own file was ADDED by the gold commit. A file that
//     did not exist at base cannot be legitimate context for work at base.
//
// ONE PORT DIFFERENCE, stated because it changes rule 3's meaning. The platform has two
// repositories (the brain repo and the source repo) and checks rule 3 against the brain's
// git history. Daijin's brain lives inside the user's repo at .daijin/, so there is one
// history and rule 3 asks the SOURCE repo whether the document's path was introduced by the
// gold commit. Same question, one fewer repository.

import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

/** Store v3 caps the exclusion at 1000 ids (CandidateFilters.excludeDocumentIds). */
export const MAX_EXCLUDED_DOCUMENT_IDS = 1_000;

const SHA = /^[0-9a-f]{7,40}$/;

async function git(repository, args, { allowFailure = false, exec = execFileAsync } = {}) {
  try {
    const { stdout } = await exec('git', args, {
      cwd: repository, encoding: 'utf8', maxBuffer: 16 * 1024 * 1024, timeout: 30_000,
    });
    return stdout.trimEnd();
  } catch (error) {
    if (allowFailure) return null;
    throw error;
  }
}

/** `web:docs/architecture.md#the-sync-seam` into its parts, or null when the source is not
 *  a sectioned reference. */
export function sourceReferenceParts(source) {
  const match = String(source || '').match(/^([A-Za-z0-9_.-]+):([^#]+)#(.+)$/);
  return match ? { branch: match[1], file: match[2], anchor: match[3] } : null;
}

/** GitHub-style anchor slug. Ported unchanged from platform/export/markdown.js, because the
 *  anchors in a brain document's source field were generated by that function and a
 *  different slug would silently match nothing. */
export function markdownAnchor(value) {
  return String(value)
    .toLowerCase()
    .replace(/[`'"“”‘’]/g, '')
    .replace(/[^\p{L}\p{N}\s-]/gu, '')
    .trim()
    .replace(/\s+/g, '-');
}

/** Split markdown into heading-rooted sections. A section runs to the next heading of the
 *  same or shallower level, so a subsection travels with its parent. */
export function splitSections(markdown) {
  const lines = String(markdown).replace(/\r\n/g, '\n').split('\n');
  const headings = [];
  for (let index = 0; index < lines.length; index += 1) {
    const match = lines[index].match(/^(#{1,6})\s+(.+?)\s*$/);
    if (match) headings.push({ index, level: match[1].length, title: match[2].trim() });
  }
  return headings.map((heading) => {
    let end = lines.length;
    for (let index = heading.index + 1; index < lines.length; index += 1) {
      const match = lines[index].match(/^(#{1,6})\s+/);
      if (match && match[1].length <= heading.level) { end = index; break; }
    }
    return {
      title: heading.title,
      level: heading.level,
      content: `${lines.slice(heading.index, end).join('\n').trimEnd()}\n`,
    };
  });
}

export function sectionAtAnchor(markdown, anchor) {
  if (anchor === 'root') return markdown;
  return splitSections(markdown || '').find((section) => markdownAnchor(section.title) === anchor)?.content || null;
}

/** Rule 1, as a pure function so every branch is testable without a repository. */
export function directGoldReason(document, exam) {
  const meta = document.meta || {};
  const source = String(meta.source || '');
  if (exam.goldCommit && (source.includes(exam.goldCommit) || meta.commit === exam.goldCommit)) {
    return 'front-matter-gold-commit';
  }
  const reference = meta.exam ?? meta.exam_id ?? meta.evaluation_of;
  const references = Array.isArray(meta.exam_ids) ? meta.exam_ids : [];
  if (reference === exam.examId || references.includes(exam.examId)) return 'evaluation-of-exam';
  if (document.type === 'evaluation' && String(document.content || '').includes(exam.examId)) {
    return 'evaluation-content-exam';
  }
  return null;
}

/**
 * Compute the exclusion for one exam.
 *
 * Returns `{ ids, reasons, truncated }`. `ids` is sorted and capped at the Store's limit;
 * `reasons` maps each id to the rule that excluded it, so a run's artifact can say WHY a
 * document was withheld rather than only that something was.
 *
 * FAILS LOUD, not open. A git failure here is not "no exclusions": it is "we do not know
 * what to withhold", and running the exam anyway would hand the student whatever the check
 * could not rule out. The caller gets an error and the run does not start.
 */
export async function computeGoldProvenanceExclusions({
  exam, documents, sourceRepo,
}, dependencies = {}) {
  if (!exam?.goldCommit || !SHA.test(String(exam.goldCommit))) {
    throw new Error('Gold-provenance exclusion needs the exam gold commit.');
  }
  if (!sourceRepo) throw new Error('Gold-provenance exclusion needs the source repository path.');
  const exec = dependencies.execFile || execFileAsync;
  const run = (args, options = {}) => git(sourceRepo, args, { ...options, exec });

  const ids = new Set();
  const reasons = new Map();
  const exclude = (document, reason) => {
    if (ids.has(document.id)) return;
    ids.add(document.id);
    reasons.set(document.id, reason);
  };

  for (const document of documents) {
    const reason = directGoldReason(document, exam);
    if (reason) exclude(document, reason);
  }

  // Which files the gold commit touched. Not allowFailure: an unknown gold commit must stop
  // the run, because every rule below is computed against it.
  const changed = new Set((await run(['diff-tree', '--no-commit-id', '--name-only', '-r', exam.goldCommit]))
    .split('\n').filter(Boolean));

  const versions = new Map();
  const fileVersions = async (file) => {
    if (!versions.has(file)) {
      versions.set(file, Promise.all([
        run(['show', `${exam.baseCommit}:${file}`], { allowFailure: true }),
        run(['show', `${exam.goldCommit}:${file}`], { allowFailure: true }),
      ]));
    }
    return versions.get(file);
  };

  for (const document of documents) {
    if (ids.has(document.id)) continue;
    const source = sourceReferenceParts(document.meta?.source);
    if (!source || !changed.has(source.file)) continue;
    const [before, after] = await fileVersions(source.file);
    // A file the gold commit DELETED has no after-version; there is no section to compare
    // and the document is stale rather than leaking.
    if (after === null) continue;
    const beforeSection = before === null ? null : sectionAtAnchor(before, source.anchor);
    const afterSection = sectionAtAnchor(after, source.anchor);
    if (afterSection !== null && beforeSection !== afterSection) exclude(document, 'source-section-changed-by-gold');
  }

  for (const document of documents) {
    if (ids.has(document.id) || !document.path) continue;
    // WALKED FROM THE GOLD COMMIT, not from HEAD. `git log` with no revision defaults to
    // HEAD, so this asked "was this file added on the branch that happens to be checked
    // out?" when the question is "did GOLD add it?". Whenever the gold commit is not
    // reachable from the working tree's HEAD - the user is on a feature branch, HEAD is
    // detached, or the gold SHA became unreachable after a squash-merge - the walk never
    // sees gold, rule 3 finds nothing, and the exclusion record still stamps `computed:
    // true` with a count of zero. Retrieval then hands the student the very lesson the gold
    // commit wrote, and certify()'s hasExclusionRecord gate passes, so the run certifies
    // "the student never saw gold" about a run in which it did. An authoritative zero
    // derived from an unfit input.
    //
    // Naming the commit also fixes the delete-and-re-add case: commits after gold are no
    // longer in the walk, so a later re-add cannot mask an add BY gold.
    const introduced = await run(['log', '--diff-filter=A', '-1', '--format=%H', exam.goldCommit, '--', document.path], { allowFailure: true });
    if (introduced && introduced === exam.goldCommit) exclude(document, 'brain-commit-introduced-by-gold');
  }

  const sorted = [...ids].sort();
  const truncated = sorted.length > MAX_EXCLUDED_DOCUMENT_IDS;
  if (truncated) {
    // The Store refuses more than 1000, so a larger exclusion cannot be honored. Refusing is
    // the only safe direction: silently dropping the tail would hand the student exactly the
    // documents that fell off the end.
    throw new Error(
      `Gold-provenance exclusion for ${exam.examId} has ${sorted.length} documents, above the store limit of `
      + `${MAX_EXCLUDED_DOCUMENT_IDS}. Refusing rather than truncating: the dropped ids are the ones that leak.`,
    );
  }
  return {
    ids: sorted,
    reasons: Object.fromEntries(reasons),
    truncated: false,
  };
}

/**
 * The exclusion RECORD that rides in the result artifact and gates certification.
 *
 * A scored run whose artifact carries no record cannot be certified (D-0020): the property
 * "the student never saw gold" is then structural rather than hoped, because a certification
 * is refused unless the run can show what it withheld and why.
 */
export function exclusionRecord(exclusion, exam) {
  if (!exclusion || !Array.isArray(exclusion.ids)) {
    throw new Error('An exclusion record needs the computed exclusion.');
  }
  return {
    goldCommit: exam.goldCommit,
    baseCommit: exam.baseCommit,
    count: exclusion.ids.length,
    ids: exclusion.ids,
    reasons: exclusion.reasons,
    // An EMPTY exclusion is a legitimate and common result (a repository whose brain has no
    // document downstream of that commit), so the record distinguishes "computed and found
    // nothing" from "never computed". Only the second refuses certification.
    computed: true,
  };
}

/** Does this artifact carry a computed exclusion? The certification gate reads this. */
export function hasExclusionRecord(artifact) {
  const record = artifact?.provenance?.goldExclusion;
  return Boolean(record && record.computed === true && Array.isArray(record.ids));
}
